export const countryCodes = [
  { code: "+351", flag: "🇵🇹", name: "Portugal",        maxDigits: 9  },
  { code: "+55",  flag: "🇧🇷", name: "Brazil",          maxDigits: 11 },
  { code: "+1",   flag: "🇺🇸", name: "USA / Canada",    maxDigits: 10 },
  { code: "+44",  flag: "🇬🇧", name: "UK",              maxDigits: 10 },
  { code: "+49",  flag: "🇩🇪", name: "Germany",         maxDigits: 11 },
  { code: "+33",  flag: "🇫🇷", name: "France",          maxDigits: 9  },
  { code: "+34",  flag: "🇪🇸", name: "Spain",           maxDigits: 9  },
  { code: "+39",  flag: "🇮🇹", name: "Italy",           maxDigits: 10 },
  { code: "+31",  flag: "🇳🇱", name: "Netherlands",     maxDigits: 9  },
  { code: "+32",  flag: "🇧🇪", name: "Belgium",         maxDigits: 9  },
  { code: "+41",  flag: "🇨🇭", name: "Switzerland",     maxDigits: 9  },
  { code: "+43",  flag: "🇦🇹", name: "Austria",         maxDigits: 10 },
  { code: "+45",  flag: "🇩🇰", name: "Denmark",         maxDigits: 8  },
  { code: "+46",  flag: "🇸🇪", name: "Sweden",          maxDigits: 9  },
  { code: "+47",  flag: "🇳🇴", name: "Norway",          maxDigits: 8  },
  { code: "+48",  flag: "🇵🇱", name: "Poland",          maxDigits: 9  },
  { code: "+353", flag: "🇮🇪", name: "Ireland",         maxDigits: 9  },
  { code: "+358", flag: "🇫🇮", name: "Finland",         maxDigits: 10 },
  { code: "+30",  flag: "🇬🇷", name: "Greece",          maxDigits: 10 },
  { code: "+36",  flag: "🇭🇺", name: "Hungary",         maxDigits: 9  },
  { code: "+420", flag: "🇨🇿", name: "Czech Republic",  maxDigits: 9  },
  { code: "+40",  flag: "🇷🇴", name: "Romania",         maxDigits: 9  },
  { code: "+359", flag: "🇧🇬", name: "Bulgaria",        maxDigits: 9  },
  { code: "+385", flag: "🇭🇷", name: "Croatia",         maxDigits: 9  },
  { code: "+352", flag: "🇱🇺", name: "Luxembourg",      maxDigits: 9  },
  { code: "+380", flag: "🇺🇦", name: "Ukraine",         maxDigits: 9  },
  { code: "+7",   flag: "🇷🇺", name: "Russia",          maxDigits: 10 },
  { code: "+90",  flag: "🇹🇷", name: "Turkey",          maxDigits: 10 },
  { code: "+91",  flag: "🇮🇳", name: "India",           maxDigits: 10 },
  { code: "+86",  flag: "🇨🇳", name: "China",           maxDigits: 11 },
  { code: "+81",  flag: "🇯🇵", name: "Japan",           maxDigits: 10 },
  { code: "+82",  flag: "🇰🇷", name: "South Korea",     maxDigits: 10 },
  { code: "+61",  flag: "🇦🇺", name: "Australia",       maxDigits: 9  },
  { code: "+64",  flag: "🇳🇿", name: "New Zealand",     maxDigits: 9  },
  { code: "+27",  flag: "🇿🇦", name: "South Africa",    maxDigits: 9  },
  { code: "+234", flag: "🇳🇬", name: "Nigeria",         maxDigits: 10 },
  { code: "+254", flag: "🇰🇪", name: "Kenya",           maxDigits: 9  },
  { code: "+212", flag: "🇲🇦", name: "Morocco",         maxDigits: 9  },
  { code: "+20",  flag: "🇪🇬", name: "Egypt",           maxDigits: 10 },
  { code: "+971", flag: "🇦🇪", name: "UAE",             maxDigits: 9  },
  { code: "+966", flag: "🇸🇦", name: "Saudi Arabia",    maxDigits: 9  },
  { code: "+972", flag: "🇮🇱", name: "Israel",          maxDigits: 9  },
  { code: "+52",  flag: "🇲🇽", name: "Mexico",          maxDigits: 10 },
  { code: "+54",  flag: "🇦🇷", name: "Argentina",       maxDigits: 10 },
  { code: "+56",  flag: "🇨🇱", name: "Chile",           maxDigits: 9  },
  { code: "+57",  flag: "🇨🇴", name: "Colombia",        maxDigits: 10 },
  { code: "+51",  flag: "🇵🇪", name: "Peru",            maxDigits: 9  },
  { code: "+58",  flag: "🇻🇪", name: "Venezuela",       maxDigits: 10 },
  { code: "+593", flag: "🇪🇨", name: "Ecuador",         maxDigits: 9  },
  { code: "+63",  flag: "🇵🇭", name: "Philippines",     maxDigits: 10 },
  { code: "+66",  flag: "🇹🇭", name: "Thailand",        maxDigits: 9  },
  { code: "+84",  flag: "🇻🇳", name: "Vietnam",         maxDigits: 9  },
  { code: "+60",  flag: "🇲🇾", name: "Malaysia",        maxDigits: 9  },
  { code: "+65",  flag: "🇸🇬", name: "Singapore",       maxDigits: 8  },
  { code: "+62",  flag: "🇮🇩", name: "Indonesia",       maxDigits: 10 },
  { code: "+92",  flag: "🇵🇰", name: "Pakistan",        maxDigits: 10 },
  { code: "+880", flag: "🇧🇩", name: "Bangladesh",      maxDigits: 10 },
  { code: "+94",  flag: "🇱🇰", name: "Sri Lanka",       maxDigits: 9  },
  { code: "+977", flag: "🇳🇵", name: "Nepal",           maxDigits: 9  },
];
